/*-
 * SPDX-License-Identifier: BSD-2-Clause-FreeBSD
 *
 * Copyright (c) 2020 Vladimir Kondratyev <wulf@FreeBSD.org>
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 */

#ifndef _ICHGPIOVAR_H_
#define _ICHGPIOVAR_H_

#define	ICHGPIO_REG_REVID		0x0000
#define	ICHGPIO_REG_REVID_MASK		0xffff0000
#define	ICHGPIO_REG_REVID_SHIFT		16
#define	ICHGPIO_REG_PADBAR		0x000C

#define	ICHGPIO_PAD_CFG0_GPIORXSTATE	0x00000001
#define	ICHGPIO_PAD_CFG0_GPIOTXSTATE	0x00000002
#define	ICHGPIO_PAD_CFG0_RXINV		0x00800000
#define	ICHGPIO_PAD_CFG0_RXEVCFG_LEVEL	0x00000000
#define	ICHGPIO_PAD_CFG0_RXEVCFG_EDGE	0x02000000
#define	ICHGPIO_PAD_CFG0_RXEVCFG_ZERO	0x04000000
#define	ICHGPIO_PAD_CFG0_RXEVCFG_MASK	0x06000000
#define	ICHGPIO_PAD_CFG0_INTSEL_MASK	0xf0000000
#define	ICHGPIO_PAD_CFG0_INTSEL_SHIFT	28

#define	ICHGPIO_PAD_CFG0_GPIOCFG_SHIFT	8
#define	ICHGPIO_PAD_CFG0_GPIOCFG_MASK	(7 << ICHGPIO_PAD_CFG0_GPIOCFG_SHIFT)
#define	ICHGPIO_PAD_CFG0_GPIOCFG_GPIO	0
#define	ICHGPIO_PAD_CFG0_GPIOCFG_GPO	1
#define	ICHGPIO_PAD_CFG0_GPIOCFG_GPI	2
#define	ICHGPIO_PAD_CFG0_GPIOCFG_HIZ	3

#define	ICHGPIO_PAD_CFG1_INTWAKECFG_MASK	0x00000007
#define	ICHGPIO_PAD_CFG1_INTWAKECFG_FALLING	0x00000001
#define	ICHGPIO_PAD_CFG1_INTWAKECFG_RISING	0x00000002
#define	ICHGPIO_PAD_CFG1_INTWAKECFG_BOTH	0x00000003
#define	ICHGPIO_PAD_CFG1_INTWAKECFG_LEVEL	0x00000004
#define	ICHGPIO_PAD_CFG1_INVRXTX_MASK		0x000000f0
#define	ICHGPIO_PAD_CFG1_INVRXTX_RXDATA		0x00000040

#endif	/* _ICHGPIOVAR_H_ */
