/*-
 * SPDX-License-Identifier: BSD-2-Clause-FreeBSD
 *
 * Copyright (c) 2020 Vladimir Kondratyev <wulf@FreeBSD.org>
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 */

#include <sys/cdefs.h>
__FBSDID("$FreeBSD$");

#include <sys/types.h>
#include <sys/bus.h>
#include <sys/kernel.h>
#include <sys/module.h>

#include <contrib/dev/acpica/include/acpi.h>
#include <dev/acpica/acpivar.h>

#include <dev/gpio/gpiobusvar.h>

#include "ichgpio_var.h"

#define	TGLLPGPIO_IRQ_STATUS	0x0100
#define	TGLLPGPIO_IRQ_MASK	0x0120

#define	TGLLPGPIO_COMMUNITY(_rid, _grps)	{	\
	.rid = (_rid),					\
	.irq_status = TGLLPGPIO_IRQ_STATUS,		\
	.irq_mask = TGLLPGPIO_IRQ_MASK,			\
	.groups = (_grps),				\
	.ngroups = nitems(_grps),			\
}

static char *tgllpgpio_ids[] = { "INT34C5", "INTC1055", "INTC1057", NULL };

/* Sunrise Point-LP */
static const ichgpio_pin_t tgllpgpio_pins[] = {
	/* Community 0 */
	/* GPP_B */
	ICHGPIO_PIN(0, "CORE_VID_0"),
	ICHGPIO_PIN(1, "CORE_VID_1"),
	ICHGPIO_PIN(2, "VRALERTB"),
	ICHGPIO_PIN(3, "CPU_GP_2"),
	ICHGPIO_PIN(4, "CPU_GP_3"),
	ICHGPIO_PIN(5, "ISH_I2C0_SDA"),
	ICHGPIO_PIN(6, "ISH_I2C0_SCL"),
	ICHGPIO_PIN(7, "ISH_I2C1_SDA"),
	ICHGPIO_PIN(8, "ISH_I2C1_SCL"),
	ICHGPIO_PIN(9, "I2C5_SDA"),
	ICHGPIO_PIN(10, "I2C5_SCL"),
	ICHGPIO_PIN(11, "PMCALERTB"),
	ICHGPIO_PIN(12, "SLP_S0B"),
	ICHGPIO_PIN(13, "PLTRSTB"),
	ICHGPIO_PIN(14, "SPKR"),
	ICHGPIO_PIN(15, "GSPI0_CS0B"),
	ICHGPIO_PIN(16, "GSPI0_CLK"),
	ICHGPIO_PIN(17, "GSPI0_MISO"),
	ICHGPIO_PIN(18, "GSPI0_MOSI"),
	ICHGPIO_PIN(19, "GSPI1_CS0B"),
	ICHGPIO_PIN(20, "GSPI1_CLK"),
	ICHGPIO_PIN(21, "GSPI1_MISO"),
	ICHGPIO_PIN(22, "GSPI1_MOSI"),
	ICHGPIO_PIN(23, "SML1ALERTB"),
	ICHGPIO_PIN(24, "GSPI0_CLK_LOOPBK"),
	ICHGPIO_PIN(25, "GSPI1_CLK_LOOPBK"),
	/* GPP_T */
	ICHGPIO_PIN(26, "I2C6_SDA"),
	ICHGPIO_PIN(27, "I2C6_SCL"),
	ICHGPIO_PIN(28, "I2C7_SDA"),
	ICHGPIO_PIN(29, "I2C7_SCL"),
	ICHGPIO_PIN(30, "UART4_RXD"),
	ICHGPIO_PIN(31, "UART4_TXD"),
	ICHGPIO_PIN(32, "UART4_RTSB"),
	ICHGPIO_PIN(33, "UART4_CTSB"),
	ICHGPIO_PIN(34, "UART5_RXD"),
	ICHGPIO_PIN(35, "UART5_TXD"),
	ICHGPIO_PIN(36, "UART5_RTSB"),
	ICHGPIO_PIN(37, "UART5_CTSB"),
	ICHGPIO_PIN(38, "UART6_RXD"),
	ICHGPIO_PIN(39, "UART6_TXD"),
	ICHGPIO_PIN(40, "UART6_RTSB"),
	ICHGPIO_PIN(41, "UART6_CTSB"),
	/* GPP_A */
	ICHGPIO_PIN(42, "ESPI_IO_0"),
	ICHGPIO_PIN(43, "ESPI_IO_1"),
	ICHGPIO_PIN(44, "ESPI_IO_2"),
	ICHGPIO_PIN(45, "ESPI_IO_3"),
	ICHGPIO_PIN(46, "ESPI_CSB"),
	ICHGPIO_PIN(47, "ESPI_CLK"),
	ICHGPIO_PIN(48, "ESPI_RESETB"),
	ICHGPIO_PIN(49, "I2S2_SCLK"),
	ICHGPIO_PIN(50, "I2S2_SFRM"),
	ICHGPIO_PIN(51, "I2S2_TXD"),
	ICHGPIO_PIN(52, "I2S2_RXD"),
	ICHGPIO_PIN(53, "PMC_I2C_SDA"),
	ICHGPIO_PIN(54, "SATAXPCIE_1"),
	ICHGPIO_PIN(55, "PMC_I2C_SCL"),
	ICHGPIO_PIN(56, "USB2_OCB_1"),
	ICHGPIO_PIN(57, "USB2_OCB_2"),
	ICHGPIO_PIN(58, "USB2_OCB_3"),
	ICHGPIO_PIN(59, "DDSP_HPD_C"),
	ICHGPIO_PIN(60, "DDSP_HPD_B"),
	ICHGPIO_PIN(61, "DDSP_HPD_1"),
	ICHGPIO_PIN(62, "DDSP_HPD_2"),
	ICHGPIO_PIN(63, "GPPC_A_21"),
	ICHGPIO_PIN(64, "GPPC_A_22"),
	ICHGPIO_PIN(65, "I2S1_SCLK"),
	ICHGPIO_PIN(66, "ESPI_CLK_LOOPBK"),
	/* Community 1 */
	/* GPP_S */
	ICHGPIO_PIN(67, "SNDW0_CLK"),
	ICHGPIO_PIN(68, "SNDW0_DATA"),
	ICHGPIO_PIN(69, "SNDW1_CLK"),
	ICHGPIO_PIN(70, "SNDW1_DATA"),
	ICHGPIO_PIN(71, "SNDW2_CLK"),
	ICHGPIO_PIN(72, "SNDW2_DATA"),
	ICHGPIO_PIN(73, "SNDW3_CLK"),
	ICHGPIO_PIN(74, "SNDW3_DATA"),
	/* GPP_H */
	ICHGPIO_PIN(75, "GPPC_H_0"),
	ICHGPIO_PIN(76, "GPPC_H_1"),
	ICHGPIO_PIN(77, "GPPC_H_2"),
	ICHGPIO_PIN(78, "SX_EXIT_HOLDOFFB"),
	ICHGPIO_PIN(79, "I2C2_SDA"),
	ICHGPIO_PIN(80, "I2C2_SCL"),
	ICHGPIO_PIN(81, "I2C3_SDA"),
	ICHGPIO_PIN(82, "I2C3_SCL"),
	ICHGPIO_PIN(83, "I2C4_SDA"),
	ICHGPIO_PIN(84, "I2C4_SCL"),
	ICHGPIO_PIN(85, "SRCCLKREQB_4"),
	ICHGPIO_PIN(86, "SRCCLKREQB_5"),
	ICHGPIO_PIN(87, "M2_SKT2_CFG_0"),
	ICHGPIO_PIN(88, "M2_SKT2_CFG_1"),
	ICHGPIO_PIN(89, "M2_SKT2_CFG_2"),
	ICHGPIO_PIN(90, "M2_SKT2_CFG_3"),
	ICHGPIO_PIN(91, "DDPB_CTRLCLK"),
	ICHGPIO_PIN(92, "DDPB_CTRLDATA"),
	ICHGPIO_PIN(93, "CPU_C10_GATEB"),
	ICHGPIO_PIN(94, "TIME_SYNC_0"),
	ICHGPIO_PIN(95, "IMGCLKOUT_1"),
	ICHGPIO_PIN(96, "IMGCLKOUT_2"),
	ICHGPIO_PIN(97, "IMGCLKOUT_3"),
	ICHGPIO_PIN(98, "IMGCLKOUT_4"),
	/* GPP_D */
	ICHGPIO_PIN(99, "ISH_GP_0"),
	ICHGPIO_PIN(100, "ISH_GP_1"),
	ICHGPIO_PIN(101, "ISH_GP_2"),
	ICHGPIO_PIN(102, "ISH_GP_3"),
	ICHGPIO_PIN(103, "IMGCLKOUT_0"),
	ICHGPIO_PIN(104, "SRCCLKREQB_0"),
	ICHGPIO_PIN(105, "SRCCLKREQB_1"),
	ICHGPIO_PIN(106, "SRCCLKREQB_2"),
	ICHGPIO_PIN(107, "SRCCLKREQB_3"),
	ICHGPIO_PIN(108, "ISH_SPI_CSB"),
	ICHGPIO_PIN(109, "ISH_SPI_CLK"),
	ICHGPIO_PIN(110, "ISH_SPI_MISO"),
	ICHGPIO_PIN(111, "ISH_SPI_MOSI"),
	ICHGPIO_PIN(112, "ISH_UART0_RXD"),
	ICHGPIO_PIN(113, "ISH_UART0_TXD"),
	ICHGPIO_PIN(114, "ISH_UART0_RTSB"),
	ICHGPIO_PIN(115, "ISH_UART0_CTSB"),
	ICHGPIO_PIN(116, "ISH_GP_4"),
	ICHGPIO_PIN(117, "ISH_GP_5"),
	ICHGPIO_PIN(118, "I2S_MCLK1_OUT"),
	ICHGPIO_PIN(119, "GSPI2_CLK_LOOPBK"),
	/* GPP_U */
	ICHGPIO_PIN(120, "UART3_RXD"),
	ICHGPIO_PIN(121, "UART3_TXD"),
	ICHGPIO_PIN(122, "UART3_RTSB"),
	ICHGPIO_PIN(123, "UART3_CTSB"),
	ICHGPIO_PIN(124, "GSPI3_CS0B"),
	ICHGPIO_PIN(125, "GSPI3_CLK"),
	ICHGPIO_PIN(126, "GSPI3_MISO"),
	ICHGPIO_PIN(127, "GSPI3_MOSI"),
	ICHGPIO_PIN(128, "GSPI4_CS0B"),
	ICHGPIO_PIN(129, "GSPI4_CLK"),
	ICHGPIO_PIN(130, "GSPI4_MISO"),
	ICHGPIO_PIN(131, "GSPI4_MOSI"),
	ICHGPIO_PIN(132, "GSPI5_CS0B"),
	ICHGPIO_PIN(133, "GSPI5_CLK"),
	ICHGPIO_PIN(134, "GSPI5_MISO"),
	ICHGPIO_PIN(135, "GSPI5_MOSI"),
	ICHGPIO_PIN(136, "GSPI6_CS0B"),
	ICHGPIO_PIN(137, "GSPI6_CLK"),
	ICHGPIO_PIN(138, "GSPI6_MISO"),
	ICHGPIO_PIN(139, "GSPI6_MOSI"),
	ICHGPIO_PIN(140, "GSPI3_CLK_LOOPBK"),
	ICHGPIO_PIN(141, "GSPI4_CLK_LOOPBK"),
	ICHGPIO_PIN(142, "GSPI5_CLK_LOOPBK"),
	ICHGPIO_PIN(143, "GSPI6_CLK_LOOPBK"),
	/* vGPIO */
	ICHGPIO_PIN(144, "CNV_BTEN"),
	ICHGPIO_PIN(145, "CNV_BT_HOST_WAKEB"),
	ICHGPIO_PIN(146, "CNV_BT_IF_SELECT"),
	ICHGPIO_PIN(147, "vCNV_BT_UART_TXD"),
	ICHGPIO_PIN(148, "vCNV_BT_UART_RXD"),
	ICHGPIO_PIN(149, "vCNV_BT_UART_CTS_B"),
	ICHGPIO_PIN(150, "vCNV_BT_UART_RTS_B"),
	ICHGPIO_PIN(151, "vCNV_MFUART1_TXD"),
	ICHGPIO_PIN(152, "vCNV_MFUART1_RXD"),
	ICHGPIO_PIN(153, "vCNV_MFUART1_CTS_B"),
	ICHGPIO_PIN(154, "vCNV_MFUART1_RTS_B"),
	ICHGPIO_PIN(155, "vUART0_TXD"),
	ICHGPIO_PIN(156, "vUART0_RXD"),
	ICHGPIO_PIN(157, "vUART0_CTS_B"),
	ICHGPIO_PIN(158, "vUART0_RTS_B"),
	ICHGPIO_PIN(159, "vISH_UART0_TXD"),
	ICHGPIO_PIN(160, "vISH_UART0_RXD"),
	ICHGPIO_PIN(161, "vISH_UART0_CTS_B"),
	ICHGPIO_PIN(162, "vISH_UART0_RTS_B"),
	ICHGPIO_PIN(163, "vCNV_BT_I2S_BCLK"),
	ICHGPIO_PIN(164, "vCNV_BT_I2S_WS_SYNC"),
	ICHGPIO_PIN(165, "vCNV_BT_I2S_SDO"),
	ICHGPIO_PIN(166, "vCNV_BT_I2S_SDI"),
	ICHGPIO_PIN(167, "vI2S2_SCLK"),
	ICHGPIO_PIN(168, "vI2S2_SFRM"),
	ICHGPIO_PIN(169, "vI2S2_TXD"),
	ICHGPIO_PIN(170, "vI2S2_RXD"),
	/* Community 4 */
	/* GPP_C */
	ICHGPIO_PIN(171, "SMBCLK"),
	ICHGPIO_PIN(172, "SMBDATA"),
	ICHGPIO_PIN(173, "SMBALERTB"),
	ICHGPIO_PIN(174, "SML0CLK"),
	ICHGPIO_PIN(175, "SML0DATA"),
	ICHGPIO_PIN(176, "SML0ALERTB"),
	ICHGPIO_PIN(177, "SML1CLK"),
	ICHGPIO_PIN(178, "SML1DATA"),
	ICHGPIO_PIN(179, "UART0_RXD"),
	ICHGPIO_PIN(180, "UART0_TXD"),
	ICHGPIO_PIN(181, "UART0_RTSB"),
	ICHGPIO_PIN(182, "UART0_CTSB"),
	ICHGPIO_PIN(183, "UART1_RXD"),
	ICHGPIO_PIN(184, "UART1_TXD"),
	ICHGPIO_PIN(185, "UART1_RTSB"),
	ICHGPIO_PIN(186, "UART1_CTSB"),
	ICHGPIO_PIN(187, "I2C0_SDA"),
	ICHGPIO_PIN(188, "I2C0_SCL"),
	ICHGPIO_PIN(189, "I2C1_SDA"),
	ICHGPIO_PIN(190, "I2C1_SCL"),
	ICHGPIO_PIN(191, "UART2_RXD"),
	ICHGPIO_PIN(192, "UART2_TXD"),
	ICHGPIO_PIN(193, "UART2_RTSB"),
	ICHGPIO_PIN(194, "UART2_CTSB"),
	/* GPP_F */
	ICHGPIO_PIN(195, "CNV_BRI_DT"),
	ICHGPIO_PIN(196, "CNV_BRI_RSP"),
	ICHGPIO_PIN(197, "CNV_RGI_DT"),
	ICHGPIO_PIN(198, "CNV_RGI_RSP"),
	ICHGPIO_PIN(199, "CNV_RF_RESET_B"),
	ICHGPIO_PIN(200, "GPPC_F_5"),
	ICHGPIO_PIN(201, "CNV_PA_BLANKING"),
	ICHGPIO_PIN(202, "GPPC_F_7"),
	ICHGPIO_PIN(203, "I2S_MCLK2_INOUT"),
	ICHGPIO_PIN(204, "BOOTMPC"),
	ICHGPIO_PIN(205, "GPPC_F_10"),
	ICHGPIO_PIN(206, "GPPC_F_11"),
	ICHGPIO_PIN(207, "GSXDOUT"),
	ICHGPIO_PIN(208, "GSXSLOAD"),
	ICHGPIO_PIN(209, "GSXDIN"),
	ICHGPIO_PIN(210, "GSXSRESETB"),
	ICHGPIO_PIN(211, "GSXCLK"),
	ICHGPIO_PIN(212, "GMII_MDC"),
	ICHGPIO_PIN(213, "GMII_MDIO"),
	ICHGPIO_PIN(214, "SRCCLKREQB_6"),
	ICHGPIO_PIN(215, "EXT_PWR_GATEB"),
	ICHGPIO_PIN(216, "EXT_PWR_GATE2B"),
	ICHGPIO_PIN(217, "VNN_CTRL"),
	ICHGPIO_PIN(218, "V1P05_CTRL"),
	ICHGPIO_PIN(219, "GPPF_CLK_LOOPBACK"),
	/* HVCMOS */
	ICHGPIO_PIN(220, "L_BKLTEN"),
	ICHGPIO_PIN(221, "L_BKLTCTL"),
	ICHGPIO_PIN(222, "L_VDDEN"),
	ICHGPIO_PIN(223, "SYS_PWROK"),
	ICHGPIO_PIN(224, "SYS_RESETB"),
	ICHGPIO_PIN(225, "MLK_RSTB"),
	/* GPP_E */
	ICHGPIO_PIN(226, "SATAXPCIE_0"),
	ICHGPIO_PIN(227, "SPI1_IO_2"),
	ICHGPIO_PIN(228, "SPI1_IO_3"),
	ICHGPIO_PIN(229, "CPU_GP_0"),
	ICHGPIO_PIN(230, "SATA_DEVSLP_0"),
	ICHGPIO_PIN(231, "SATA_DEVSLP_1"),
	ICHGPIO_PIN(232, "GPPC_E_6"),
	ICHGPIO_PIN(233, "CPU_GP_1"),
	ICHGPIO_PIN(234, "SPI1_CS1B"),
	ICHGPIO_PIN(235, "USB2_OCB_0"),
	ICHGPIO_PIN(236, "SPI1_CSB"),
	ICHGPIO_PIN(237, "SPI1_CLK"),
	ICHGPIO_PIN(238, "SPI1_MISO_IO_1"),
	ICHGPIO_PIN(239, "SPI1_MOSI_IO_0"),
	ICHGPIO_PIN(240, "DDSP_HPD_A"),
	ICHGPIO_PIN(241, "ISH_GP_6"),
	ICHGPIO_PIN(242, "ISH_GP_7"),
	ICHGPIO_PIN(243, "GPPC_E_17"),
	ICHGPIO_PIN(244, "DDP1_CTRLCLK"),
	ICHGPIO_PIN(245, "DDP1_CTRLDATA"),
	ICHGPIO_PIN(246, "DDP2_CTRLCLK"),
	ICHGPIO_PIN(247, "DDP2_CTRLDATA"),
	ICHGPIO_PIN(248, "DDPA_CTRLCLK"),
	ICHGPIO_PIN(249, "DDPA_CTRLDATA"),
	ICHGPIO_PIN(250, "SPI1_CLK_LOOPBK"),
	/* JTAG */
	ICHGPIO_PIN(251, "JTAG_TDO"),
	ICHGPIO_PIN(252, "JTAGX"),
	ICHGPIO_PIN(253, "PRDYB"),
	ICHGPIO_PIN(254, "PREQB"),
	ICHGPIO_PIN(255, "CPU_TRSTB"),
	ICHGPIO_PIN(256, "JTAG_TDI"),
	ICHGPIO_PIN(257, "JTAG_TMS"),
	ICHGPIO_PIN(258, "JTAG_TCK"),
	ICHGPIO_PIN(259, "DBG_PMODE"),
	/* Community 5 */
	/* GPP_R */
	ICHGPIO_PIN(260, "HDA_BCLK"),
	ICHGPIO_PIN(261, "HDA_SYNC"),
	ICHGPIO_PIN(262, "HDA_SDO"),
	ICHGPIO_PIN(263, "HDA_SDI_0"),
	ICHGPIO_PIN(264, "HDA_RSTB"),
	ICHGPIO_PIN(265, "HDA_SDI_1"),
	ICHGPIO_PIN(266, "GPP_R_6"),
	ICHGPIO_PIN(267, "GPP_R_7"),
	/* SPI */
	ICHGPIO_PIN(268, "SPI0_IO_2"),
	ICHGPIO_PIN(269, "SPI0_IO_3"),
	ICHGPIO_PIN(270, "SPI0_MOSI_IO_0"),
	ICHGPIO_PIN(271, "SPI0_MISO_IO_1"),
	ICHGPIO_PIN(272, "SPI0_TPM_CSB"),
	ICHGPIO_PIN(273, "SPI0_FLASH_0_CSB"),
	ICHGPIO_PIN(274, "SPI0_FLASH_1_CSB"),
	ICHGPIO_PIN(275, "SPI0_CLK"),
	ICHGPIO_PIN(276, "SPI0_CLK_LOOPBK"),
};

static const ichgpio_group_t tglgpio_comm0_groups[] = {
	ICHGPIO_GROUP(0, 26),			/* GPP_B */
	ICHGPIO_GROUP(32, 16),			/* GPP_T */
	ICHGPIO_GROUP(64, 25),			/* GPP_A */
};
static const ichgpio_group_t tglgpio_comm1_groups[] = {
	ICHGPIO_GROUP(96, 8),			/* GPP_S */
	ICHGPIO_GROUP(128, 24),			/* GPP_H */
	ICHGPIO_GROUP(160, 21),			/* GPP_D */
	ICHGPIO_GROUP(192, 24),			/* GPP_U */
	ICHGPIO_GROUP(224, 27),			/* vGPIO */
};
static const ichgpio_group_t tglgpio_comm4_groups[] = {
	ICHGPIO_GROUP(256, 24),			/* GPP_C */
	ICHGPIO_GROUP(288, 25),			/* GPP_F */
	ICHGPIO_GROUP(ICHGPIO_NOBASE, 6),	/* HVCMOS */
	ICHGPIO_GROUP(320, 25),			/* GPP_E */
	ICHGPIO_GROUP(ICHGPIO_NOBASE, 9),	/* JTAG */
};

static const ichgpio_group_t tglgpio_comm5_groups[] = {
	ICHGPIO_GROUP(352, 8),			/* GPP_R */
	ICHGPIO_GROUP(ICHGPIO_NOBASE, 9),	/* SPI */
};

static const ichgpio_comm_t tgllpgpio_comms[] = {
	TGLLPGPIO_COMMUNITY(0, tglgpio_comm0_groups),
	TGLLPGPIO_COMMUNITY(1, tglgpio_comm1_groups),
	TGLLPGPIO_COMMUNITY(2, tglgpio_comm4_groups),
	TGLLPGPIO_COMMUNITY(3, tglgpio_comm5_groups),
};

static int
tgllpgpio_probe(device_t dev)
{
	ACPI_HANDLE handle;
	int rv;
	int uid;

	if (acpi_disabled("tgllpgpio"))
		return (ENXIO);

	rv = ACPI_ID_PROBE(device_get_parent(dev), dev, tgllpgpio_ids, NULL);
	if (rv > 0)
		return (rv);

	handle = acpi_get_handle(dev);
	if (ACPI_FAILURE(acpi_GetInteger(handle, "_UID", &uid)))
		uid = 0;
	if (uid != 0)	/* SW_UID */
		return (ENXIO);

	device_set_desc(dev, "Intel Tiger Lake-LP PCH GPIO");

	return (rv);
}

static int
tgllpgpio_attach(device_t dev)
{
	ICHGPIO_REGISTER_DATA(dev, tgllpgpio_comms, tgllpgpio_pins);

	return (ichgpio_attach(dev));
}

static device_method_t tgllpgpio_methods[] = {
	DEVMETHOD(device_probe,     	tgllpgpio_probe),
	DEVMETHOD(device_attach,	tgllpgpio_attach),
	DEVMETHOD(device_detach,	ichgpio_detach),

	/* GPIO protocol */
	DEVMETHOD(gpio_get_bus,		ichgpio_get_bus),
	DEVMETHOD(gpio_pin_max,		ichgpio_pin_max),
	DEVMETHOD(gpio_pin_getname,	ichgpio_pin_getname),
	DEVMETHOD(gpio_pin_getflags,	ichgpio_pin_getflags),
	DEVMETHOD(gpio_pin_getcaps,	ichgpio_pin_getcaps),
	DEVMETHOD(gpio_pin_setflags,	ichgpio_pin_setflags),
	DEVMETHOD(gpio_pin_get,		ichgpio_pin_get),
	DEVMETHOD(gpio_pin_set,		ichgpio_pin_set),
	DEVMETHOD(gpio_pin_toggle,	ichgpio_pin_toggle),

	DEVMETHOD_END
};

DEFINE_CLASS_0(ichgpio, tgllpgpio_driver, tgllpgpio_methods,
    sizeof(struct ichgpio_softc));
DRIVER_MODULE(tgllpgpio, acpi, tgllpgpio_driver, ichgpio_devclass, NULL, 0);
MODULE_DEPEND(tgllpgpio, acpi, 1, 1, 1);
MODULE_DEPEND(tgllpgpio, ichgpio, 1, 1, 1);
MODULE_VERSION(tgllpgpio, 1);
ACPI_PNP_INFO(tgllpgpio_ids);
